### PR TITLE
Do not allow n_lists to exceed number of rows for RAFT IVF

### LINKED ISSUE #229: RAFT build fail when set M = 0
As the code below:
```
        KNOWHERE_CONFIG_DECLARE_FIELD(m).set_default(8).description("m").set_range(0, 65536).for_train();
        KNOWHERE_CONFIG_DECLARE_FIELD(nbits)
            .set_default(8)
            .description("nbits")
            .set_range(4, 8)  // Declared in base but limited here
            .for_train();
```

the valid build param range for RAFT should be:
m: [0, 65536]

however when set "m = 0", RAFT still report error and print out stack frames:
```
I1128 18:32:10.891585 932838 factory.cc:20] [KNOWHERE][Create][python] create knowhere index GPU_RAFT_IVF_PQ with version 1
E1128 18:32:15.192901 932838 config.h:317] [KNOWHERE][Load][python] Out of range in json: param [m] should be in [0, 65536].
E1128 18:32:18.832428 932838 gpu_raft.h:92] [KNOWHERE][Train][python] RAFT failure at file=/home/caiyd/vec/tmp/knowhere/build/Release/_deps/raft-src/cpp/include/raft/neighbors/detail/ivf_pq_build.cuh line=1766: number of rows can't be less than n_lists
Obtained 64 stack frames
#0 in /home/caiyd/.virtualenvs/knowhere-test/lib/python3.8/site-packages/knowhere/libknowhere.so(_ZN4raft9exception18collect_call_stackEv+0x52) [0x7f29278e7d52]
#1 in /home/caiyd/.virtualenvs/knowhere-test/lib/python3.8/site-packages/knowhere/libknowhere.so(_ZN4raft11logic_errorC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xd1) [0x7f29278e9b51]
#2 in /home/caiyd/.virtualenvs/knowhere-test/lib/python3.8/site-packages/knowhere/libknowhere.so(_ZN4raft9neighbors6ivf_pq6detail5buildIflEENS1_5indexIT0_EERKNS_9resourcesERKNS1_12index_paramsEPKT_S5_j+0x123d) [0x7f2927af9f9d]
#3 in /home/caiyd/.virtualenvs/knowhere-test/lib/python3.8/site-packages/knowhere/libknowhere.so(_ZN13raft_knowhere19raft_knowhere_indexILN10raft_proto15raft_index_kindE1EE4impl5trainERKNS_20raft_knowhere_configEPKfll+0x365) [0x7f2927db10e5]
#4 in /home/caiyd/.virtualenvs/knowhere-test/lib/python3.8/site-packages/knowhere/libknowhere.so(_ZN8knowhere16GpuRaftIndexNodeILN10raft_proto15raft_index_kindE1EE5TrainERKNS_7DataSetERKNS_6ConfigE+0x1312) [0x7f2927df5572]
#5 in /home/caiyd/.virtualenvs/knowhere-test/lib/python3.8/site-packages/knowhere/libknowhere.so(_ZN8knowhere5IndexINS_9IndexNodeEE5BuildERKNS_7DataSetERKN8nlohmann16json_abi_v3_11_210basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS7_14adl_serializerESA_IhSaIhEEEE+0x206) [0x7f29277a9296]
#6 in /home/caiyd/.virtualenvs/knowhere-test/lib/python3.8/site-packages/knowhere/_swigknowhere.cpython-38-x86_64-linux-gnu.so(+0x3f13d) [0x7f293e58713d]
```

test case: test_basic.TestBasic.test_raft_ivf_pq_build_param

### PR DESCRIPTION
**Pull request by wphicks**
Cap the maximum value of n_lists in RAFT IVF and IVFPQ configurations at the number of rows used for training.

Revert change to default and range for "m" for RAFT indexes, since I believe that this change was due to a misidentification of the underlying issue.

/issue: #229

### CODE REVIEW

File: src/index/gpu_raft/gpu_raft_ivf_pq_config.h [hunk 1]
```diff
@@ -46,7 +46,7 @@ struct GpuRaftIvfPqConfig : public IvfPqConfig {
             .description("search for top k similar vector.")
             .set_range(1, 1024)  // Declared in base but limited to 1024
             .for_search();
-        KNOWHERE_CONFIG_DECLARE_FIELD(m).set_default(8).description("m").set_range(1, 65536).for_train();
+        KNOWHERE_CONFIG_DECLARE_FIELD(m).set_default(0).description("m").set_range(0, 65536).for_train();
```
Comment (Presburger) [inline src/index/gpu_raft/gpu_raft_ivf_pq_config.h:49]: If m is set to 0, does it mean auto? We ran some tests here, and setting m to 0 caused some issues.

**Review by Presburger — APPROVED** [review]

**Comment by Presburger** [comment]
\lgtm
